/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sschudakov.xml.xml_view;

import com.sschudakov.utils.ExceptionRenderer;
import com.sschudakov.xml.bin.Event;
import com.sschudakov.xml.bin.Events;

import javax.swing.*;
import java.util.List;

/**
 * @author Semen
 */
public class XMLViewManager extends javax.swing.JFrame {


    /**
     * Creates new form XMLViewManager
     */
    public XMLViewManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaPanel = new javax.swing.JPanel();
        textAreaScrollPane = new javax.swing.JScrollPane();
        textPanel = new javax.swing.JTextPane();
        parametersPanel = new javax.swing.JPanel();
        domRadioButton = new javax.swing.JRadioButton();
        saxRadioButton = new javax.swing.JRadioButton();
        staxRadioButton = new javax.swing.JRadioButton();
        marshallingRadioButton = new javax.swing.JRadioButton();
        facultyCheckBox = new javax.swing.JCheckBox();
        subFacultyCheckBox = new javax.swing.JCheckBox();
        branchOfStudyCheckBox = new javax.swing.JCheckBox();
        dateCheckBox = new javax.swing.JCheckBox();
        facultyComboBox = new javax.swing.JComboBox<>();
        subFacultyComboBox = new javax.swing.JComboBox<>();
        branchOfStudyComboBox = new javax.swing.JComboBox<>();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        firstNameCheckBox = new javax.swing.JCheckBox();
        middleNameCheckBox = new javax.swing.JCheckBox();
        lastNameCheckBox = new javax.swing.JCheckBox();
        firstNameTextField = new javax.swing.JTextField();
        middleNameTextFiled = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        toHtmlButton = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaScrollPane.setViewportView(textPanel);


        javax.swing.GroupLayout textAreaPanelLayout = new javax.swing.GroupLayout(textAreaPanel);
        textAreaPanel.setLayout(textAreaPanelLayout);
        textAreaPanelLayout.setHorizontalGroup(
                textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 365, Short.MAX_VALUE)
                        .addGroup(textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(textAreaPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(textAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        textAreaPanelLayout.setVerticalGroup(
                textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(textAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(textAreaPanelLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(textAreaScrollPane)
                                        .addGap(6, 6, 6)))
        );

        domRadioButton.setText("DOM");

        saxRadioButton.setText("SAX");


        staxRadioButton.setText("StAX");


        marshallingRadioButton.setText("Marshalling");


        facultyCheckBox.setText("faculty");


        subFacultyCheckBox.setText("sub faculty");


        branchOfStudyCheckBox.setText("branch of study");


        dateCheckBox.setText("date");


        fromLabel.setText("from");

        toLabel.setText("to");

        searchButton.setText("search");


        cleanButton.setText("clean");


        toHtmlButton.setText("to html");


        firstNameCheckBox.setText("first name");

        middleNameCheckBox.setText("middle name");

        lastNameCheckBox.setText("last name");



        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
                parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(subFacultyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(facultyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(facultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(subFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(branchOfStudyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                                                .addComponent(dateCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                                .addComponent(firstNameCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(4, 4, 4)))
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                                                                .addComponent(fromTextField)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(firstNameTextField)
                                                        .addComponent(middleNameTextFiled)
                                                        .addComponent(lastNameTextField)
                                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                                .addComponent(branchOfStudyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(middleNameCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lastNameCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                                                .addGap(0, 0, 0)
                                                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(saxRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(staxRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(marshallingRadioButton)
                                                                        .addComponent(domRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(toHtmlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        parametersPanelLayout.setVerticalGroup(
                parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(facultyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(facultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(subFacultyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(subFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(branchOfStudyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(branchOfStudyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(middleNameCheckBox)
                                        .addComponent(middleNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lastNameCheckBox)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toHtmlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(domRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saxRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staxRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marshallingRadioButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textAreaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        additionalInits();
        pack();
    }

    private void additionalInits() {

        this.selector = new EventsSelector(this.facultyCheckBox, this.subFacultyCheckBox, this.branchOfStudyCheckBox,
                this.dateCheckBox, this.firstNameCheckBox, this.middleNameCheckBox, this.lastNameCheckBox,
                this.facultyComboBox, this.subFacultyComboBox, this.branchOfStudyComboBox,
                this.fromTextField, this.toTextField,
                this.firstNameTextField, this.middleNameTextFiled, this.lastNameTextField);

        this.documentReader = new XMLDocumentReader(
                this.domRadioButton, this.saxRadioButton,
                this.staxRadioButton, this.marshallingRadioButton
        );

        textAreaScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        textAreaScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        domRadioButton.addActionListener(this::domRadioButtonActionPerformed);
        saxRadioButton.addActionListener(this::saxRadioButtonActionPerformed);
        staxRadioButton.addActionListener(this::staxRadioButtonActionPerformed);
        marshallingRadioButton.addActionListener(this::marshallingRadioButtonActionPerformed);

        searchButton.addActionListener(this::searchButtonActionPerformed);
        cleanButton.addActionListener(this::cleanButtonActionPerformed);
        toHtmlButton.addActionListener(this::toHtmlButtonActionPerformed);

        domRadioButton.setSelected(true);
    }


    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Events events = this.documentReader.read(PATH_TO_XML);
            List<Event> selectedEvents = this.selector.selectEvents(events);
            this.textPanel.setText(formRenderingString(selectedEvents));
        } catch (Exception e) {
            ExceptionRenderer.renderException(this, e);
            e.printStackTrace();
        }
    }

    private static String formRenderingString(List<Event> eventList) {
        StringBuilder result = new StringBuilder("");
        for (Event event : eventList) {
            result.append("event:\n " + event.toString() + "\n");
        }
        return result.toString();
    }

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void toHtmlButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }


    private void domRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domRadioButtonActionPerformed

        if (this.domRadioButton.isSelected()) {
            this.saxRadioButton.setSelected(false);
            this.staxRadioButton.setSelected(false);
            this.marshallingRadioButton.setSelected(false);
        } else {
            this.domRadioButton.setSelected(true);
        }
    }

    private void saxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domRadioButtonActionPerformed
        if (this.saxRadioButton.isSelected()) {
            this.domRadioButton.setSelected(false);
            this.staxRadioButton.setSelected(false);
            this.marshallingRadioButton.setSelected(false);
        } else {
            this.saxRadioButton.setSelected(true);
        }
    }

    private void staxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domRadioButtonActionPerformed
        if (this.staxRadioButton.isSelected()) {
            this.domRadioButton.setSelected(false);
            this.saxRadioButton.setSelected(false);
            this.marshallingRadioButton.setSelected(false);
        } else {
            this.staxRadioButton.setSelected(true);
        }
    }

    private void marshallingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domRadioButtonActionPerformed
        if (this.marshallingRadioButton.isSelected()) {
            this.domRadioButton.setSelected(false);
            this.saxRadioButton.setSelected(false);
            this.staxRadioButton.setSelected(false);
        } else {
            this.marshallingRadioButton.setSelected(true);
        }
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(com.sschudakov.xml.xml_view.XMLViewManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(com.sschudakov.xml.xml_view.XMLViewManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(com.sschudakov.xml.xml_view.XMLViewManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(com.sschudakov.xml.xml_view.XMLViewManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new com.sschudakov.xml.xml_view.XMLViewManager().setVisible(true);
            }
        });
    }


    private static final String PATH_TO_XML = "D:\\Workspace.java\\FirstLab\\xml\\student_government_events.xml";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox facultyCheckBox;
    private javax.swing.JCheckBox subFacultyCheckBox;
    private javax.swing.JCheckBox branchOfStudyCheckBox;
    private javax.swing.JCheckBox dateCheckBox;

    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField toTextField;

    private javax.swing.JCheckBox firstNameCheckBox;
    private javax.swing.JCheckBox middleNameCheckBox;
    private javax.swing.JCheckBox lastNameCheckBox;

    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField middleNameTextFiled;
    private javax.swing.JTextField lastNameTextField;

    private javax.swing.JComboBox<String> facultyComboBox;
    private javax.swing.JComboBox<String> subFacultyComboBox;
    private javax.swing.JComboBox<String> branchOfStudyComboBox;


    private javax.swing.JButton searchButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton toHtmlButton;

    private javax.swing.JRadioButton domRadioButton;
    private javax.swing.JRadioButton saxRadioButton;
    private javax.swing.JRadioButton staxRadioButton;
    private javax.swing.JRadioButton marshallingRadioButton;

    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel toLabel;

    private javax.swing.JPanel parametersPanel;
    private javax.swing.JPanel textAreaPanel;

    private javax.swing.JScrollPane textAreaScrollPane;
    private javax.swing.JTextPane textPanel;

    private EventsSelector selector;
    private XMLDocumentReader documentReader;
    // End of variables declaration//GEN-END:variables
}
